//! Generated gateway bootstrap for sdkwork-documents.
//! Regenerated by pnpm gateway:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_documents_app_api::gateway_mount(api));
    router = router.merge(sdkwork_routes_documents_backend_api::gateway_mount(api));
    router = router.merge(sdkwork_routes_documents_open_api::gateway_mount(api));
    ApplicationAssembly { router }
}
