$ErrorActionPreference = "Stop"

function Remove-GeneratedSdkBuildArtifacts {
    param(
        [Parameter(Mandatory = $true)][string[]]$SdkRoots
    )

    foreach ($sdkRoot in $SdkRoots) {
        foreach ($artifactName in @("node_modules", "dist", "package-lock.json")) {
            $artifactPath = Join-Path $sdkRoot $artifactName
            if (Test-Path $artifactPath) {
                Remove-Item -LiteralPath $artifactPath -Recurse -Force
            }
        }
    }
}

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
    )
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
    }
}

function Read-JsonFile {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (!(Test-Path $Path)) { throw "Missing required file: $Path" }
    return Get-Content -Raw $Path | ConvertFrom-Json
}

$documentsDesignPath = "docs/superpowers/specs/2026-06-20-documents-architecture-design.md"
$documentsDesign = Get-Content -Raw $documentsDesignPath

$canonicalSdkGeneratorRoot = "..\sdkwork-sdk-generator"
$canonicalSdkGeneratorCli = "..\sdkwork-sdk-generator\bin\sdkgen.js"
$staleSdkGeneratorRoot = "..\..\sdkwork-sdk-generator"

if (!$documentsDesign.Contains($canonicalSdkGeneratorRoot) -or !$documentsDesign.Contains($canonicalSdkGeneratorCli)) {
    throw "$documentsDesignPath must document the canonical sdkwork-sdk-generator path and CLI entrypoint"
}

if ($documentsDesign.Contains($staleSdkGeneratorRoot)) {
    throw "$documentsDesignPath still references the old sdkwork-sdk-generator path: $staleSdkGeneratorRoot"
}

$requiredSdkStandardSnippets = @(
    "All SDKWork Documents HTTP SDKs MUST be generated by the canonical SDKWork generator",
    "--standard-profile sdkwork-v3",
    "--fixed-sdk-version 0.1.0",
    "sdkwork-sdk.json",
    ".sdkwork/sdkwork-generator-manifest.json",
    ".sdkwork/sdkwork-generator-changes.json",
    ".sdkwork/sdkwork-generator-report.json",
    "custom/",
    "node_modules/",
    "dist/",
    "package-lock.json"
)

foreach ($snippet in $requiredSdkStandardSnippets) {
    if (!$documentsDesign.Contains($snippet)) {
        throw "$documentsDesignPath must document SDK generation standard snippet: $snippet"
    }
}

Invoke-Checked powershell -ExecutionPolicy Bypass -File tools/verify_sdkwork_structure.ps1

$requiredFiles = @(
    "AGENTS.md", "CODEX.md", "CLAUDE.md", "GEMINI.md",
    ".sdkwork/README.md", ".sdkwork/skills/README.md", ".sdkwork/plugins/README.md",
    "sdkwork.app.config.json", "specs/README.md", "specs/component.spec.json",
    "docs/superpowers/specs/2026-06-20-documents-architecture-design.md",
    "docs/schema-registry/README.md",
    "docs/schema-registry/tables/001-documents-core.yaml",
    "sdks/README.md",
    "sdks/sdkwork-documents-sdk/.sdkwork-assembly.json",
    "sdks/sdkwork-documents-app-sdk/.sdkwork-assembly.json",
    "sdks/sdkwork-documents-backend-sdk/.sdkwork-assembly.json",
    "apis/authority-manifest.json",
    "database/database.manifest.json",
    "package.json", "sdkwork.workflow.json", ".github/workflows/package.yml",
    ".github/workflows/verify.yml",
    "Cargo.toml"
)

foreach ($file in $requiredFiles) {
    if (!(Test-Path $file)) { throw "Missing required phase1 artifact: $file" }
}

$appConfig = Read-JsonFile "sdkwork.app.config.json"
if ($appConfig.app.key -ne "sdkwork-documents") {
    throw "sdkwork.app.config.json app.key must be sdkwork-documents"
}

$rootSpec = Read-JsonFile "specs/component.spec.json"
if ($rootSpec.component.domain -ne "content" -or $rootSpec.component.capability -ne "documents") {
    throw "Root component spec must use domain=content and capability=documents"
}

$canonicalSpecFiles = @("SDK_SPEC.md", "SDK_WORKSPACE_GENERATION_SPEC.md")
foreach ($specFile in $canonicalSpecFiles) {
    $found = $false
    foreach ($entry in $rootSpec.canonicalSpecs) {
        if ($entry.file -eq $specFile) {
            $found = $true
            break
        }
    }
    if (!$found) {
        throw "specs/component.spec.json canonicalSpecs must include $specFile"
    }
}

$routerTests = @{
    "sdkwork-routes-documents-open-api" = @("open_api_routes.rs", "open_web_framework_routes.rs", "open_openapi_routes.rs")
    "sdkwork-routes-documents-app-api" = @("app_api_routes.rs", "app_web_framework_routes.rs", "app_openapi_routes.rs")
    "sdkwork-routes-documents-backend-api" = @("backend_api_routes.rs", "backend_web_framework_routes.rs", "backend_openapi_routes.rs")
}
foreach ($entry in $routerTests.GetEnumerator()) {
    foreach ($testFile in $entry.Value) {
        $path = "crates/$($entry.Key)/tests/$testFile"
        if (!(Test-Path $path)) {
            throw "Missing router contract test: $path"
        }
    }
}

$hostedRuntimeTest = "crates/sdkwork-routes-documents-app-api/tests/hosted_runtime_routes.rs"
if (!(Test-Path $hostedRuntimeTest)) {
    throw "Missing hosted runtime integration test: $hostedRuntimeTest"
}

$rootRuntimeEntrypoints = @(
    "sdkwork-documents-app-api",
    "sdkwork-documents-backend-api",
    "sdkwork-documents-open-api",
    "crates/sdkwork-routes-documents-app-api/src/runtime.rs"
)
foreach ($entrypoint in $rootRuntimeEntrypoints) {
    $found = $false
    foreach ($value in @($rootSpec.contracts.runtimeEntrypoints)) {
        if ($value -eq $entrypoint) {
            $found = $true
            break
        }
    }
    if (!$found) {
        throw "specs/component.spec.json contracts.runtimeEntrypoints must include $entrypoint"
    }
}

Invoke-Checked node tools/patch-route-manifest-extensions.mjs
Invoke-Checked powershell -ExecutionPolicy Bypass -File tools/verify_openapi_operation_ids.ps1
Invoke-Checked node sdks/standardize-documents-sdk-family.mjs --check
Invoke-Checked node tools/materialize-apis-authority.mjs --check
Invoke-Checked node tools/check_sdkwork_ai_prod_architecture_alignment.mjs
Invoke-Checked node sdks/test/verify-sdk-ownership-boundaries.test.mjs

$requiredGeneratedSdkRoots = @(
    "sdks/sdkwork-documents-sdk/sdkwork-documents-sdk-typescript/generated/server-openapi",
    "sdks/sdkwork-documents-app-sdk/sdkwork-documents-app-sdk-typescript/generated/server-openapi",
    "sdks/sdkwork-documents-backend-sdk/sdkwork-documents-backend-sdk-typescript/generated/server-openapi"
)

Remove-GeneratedSdkBuildArtifacts -SdkRoots $requiredGeneratedSdkRoots

$requiredGeneratedSdkFiles = @(
    "sdkwork-sdk.json",
    "package.json",
    "tsconfig.json",
    "bin/publish-core.mjs",
    ".sdkwork/sdkwork-generator-manifest.json",
    ".sdkwork/sdkwork-generator-changes.json",
    ".sdkwork/sdkwork-generator-report.json"
)

foreach ($sdkRoot in $requiredGeneratedSdkRoots) {
    if (!(Test-Path $sdkRoot)) {
        throw "Missing generated SDK output root: $sdkRoot"
    }

    foreach ($requiredFile in $requiredGeneratedSdkFiles) {
        $requiredPath = Join-Path $sdkRoot $requiredFile
        if (!(Test-Path $requiredPath)) {
            throw "Missing generated SDK control/source file: $requiredPath"
        }
    }

    foreach ($requiredDirectory in @("src", "custom")) {
        $requiredPath = Join-Path $sdkRoot $requiredDirectory
        if (!(Test-Path $requiredPath -PathType Container)) {
            throw "Missing generated SDK directory: $requiredPath"
        }
    }

    $manifest = Get-Content -Raw (Join-Path $sdkRoot ".sdkwork/sdkwork-generator-manifest.json") | ConvertFrom-Json
    if (!$manifest.generatedFiles -or $manifest.generatedFiles.Count -eq 0) {
        throw "Generated SDK manifest has no generatedFiles entries: $sdkRoot"
    }

    foreach ($entry in $manifest.generatedFiles) {
        $generatedPath = [string]$entry.path
        if (
            $generatedPath.StartsWith("dist/") `
            -or $generatedPath.StartsWith("node_modules/") `
            -or $generatedPath -eq "package-lock.json"
        ) {
            throw "Generated SDK manifest must not include local build artifact: $sdkRoot/$generatedPath"
        }
    }
}

$generatedSdkBuildArtifacts = @()
foreach ($sdkRoot in $requiredGeneratedSdkRoots) {
    foreach ($artifactName in @("node_modules", "dist", "package-lock.json")) {
        $artifactPath = Join-Path $sdkRoot $artifactName
        if (Test-Path $artifactPath) {
            $generatedSdkBuildArtifacts += $artifactPath
        }
    }
}
if ($generatedSdkBuildArtifacts.Count -gt 0) {
    throw "Generated SDK roots must not contain local build artifacts: $($generatedSdkBuildArtifacts -join ', ')"
}

$packages = @(
    "sdkwork-documents-contract",
    "sdkwork-documents-database-host",
    "sdkwork-content-documents-service",
    "sdkwork-content-documents-repository-sqlx",
    "sdkwork-content-documents-sdk-reference",
    "sdkwork-routes-documents-app-api",
    "sdkwork-routes-documents-backend-api",
    "sdkwork-routes-documents-open-api",
    "sdkwork-documents-api-server",
    "sdkwork-documents-observability"
)

foreach ($package in $packages) {
    Invoke-Checked cargo fmt -p $package --check
}

Invoke-Checked cargo test --workspace

if (!$documentsDesign.Contains("Tables use documents_ prefix")) {
    throw "$documentsDesignPath must document the SDKWork Documents documents_ database object naming standard"
}

$databaseObjectSearchRoots = @(
    "crates/sdkwork-content-documents-repository-sqlx/migrations",
    "crates/sdkwork-content-documents-repository-sqlx/src",
    "crates/sdkwork-content-documents-repository-sqlx/tests"
)

$oldDatabaseObjectPatterns = @(
    "CREATE TABLE IF NOT EXISTS document_",
    "CREATE INDEX IF NOT EXISTS idx_document_",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_document_",
    "FROM document_",
    "INSERT INTO document_",
    "UPDATE document_",
    "JOIN document_",
    "pragma_table_info('document_"
)

function Get-DefinedDatabaseObjects {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,
        [Parameter(Mandatory = $true)]
        [string]$Prefix
    )

    $objects = New-Object System.Collections.Generic.List[string]
    foreach ($line in $Content -split "`n") {
        $trimmed = $line.Trim()
        if ($trimmed.StartsWith($Prefix)) {
            $tail = $trimmed.Substring($Prefix.Length).Trim()
            $name = ($tail -split "\s+")[0].Trim('"')
            if (![string]::IsNullOrWhiteSpace($name)) {
                $objects.Add($name)
            }
        }
    }
    return $objects
}

foreach ($root in $databaseObjectSearchRoots) {
    foreach ($path in Get-ChildItem -Path $root -Recurse -File) {
        if ($path.Name -eq "migration_manifest.rs") {
            continue
        }

        $content = Get-Content -Raw $path.FullName
        foreach ($pattern in $oldDatabaseObjectPatterns) {
            if ($content.Contains($pattern)) {
                throw "Old document_ database object usage remains in $($path.FullName): $pattern"
            }
        }

        foreach ($table in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE TABLE IF NOT EXISTS ") {
            if (!$table.StartsWith("documents_")) {
                throw "Documents database table must use documents_ prefix in $($path.FullName): $table"
            }
        }

        foreach ($index in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE INDEX IF NOT EXISTS ") {
            if (!$index.StartsWith("idx_documents_")) {
                throw "Documents database index must use idx_documents_ prefix in $($path.FullName): $index"
            }
        }

        foreach ($index in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE UNIQUE INDEX IF NOT EXISTS ") {
            if (!$index.StartsWith("uk_documents_")) {
                throw "Documents database unique index must use uk_documents_ prefix in $($path.FullName): $index"
            }
        }
    }
}

$gitignore = Get-Content -Raw ".gitignore"
foreach ($ignoredArtifact in @(
    "sdks/**/generated/server-openapi/node_modules/",
    "sdks/**/generated/server-openapi/dist/",
    "sdks/**/generated/server-openapi/package-lock.json"
)) {
    if (!$gitignore.Contains($ignoredArtifact)) {
        throw ".gitignore must ignore generated SDK local build artifact: $ignoredArtifact"
    }
}

Write-Host "SDKWork Documents phase1 contract verification passed."
