environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.sdkwork.com", "documents-admin.sdkwork.com", "documents-open.sdkwork.com", "doc.sdkwork.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.birdcoder.com", "documents-admin.birdcoder.com", "documents-open.birdcoder.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.dtupay.com", "documents-admin.dtupay.com", "documents-open.dtupay.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.noaper.com", "documents-admin.noaper.com", "documents-open.noaper.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "noaper.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.sdkwork.cn", "documents-admin.sdkwork.cn", "documents-open.sdkwork.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.birdcoder.cn", "documents-admin.birdcoder.cn", "documents-open.birdcoder.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.dtupay.cn", "documents-admin.dtupay.cn", "documents-open.dtupay.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.noaper.cn", "documents-admin.noaper.cn", "documents-open.noaper.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "noaper.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.skubc.com", "documents-admin.skubc.com", "documents-open.skubc.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.skubc.cn", "documents-admin.skubc.cn", "documents-open.skubc.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.zowalk.com", "documents-admin.zowalk.com", "documents-open.zowalk.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.zowalk.cn", "documents-admin.zowalk.cn", "documents-open.zowalk.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.offer86.com", "documents-admin.offer86.com", "documents-open.offer86.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.offer86.cn", "documents-admin.offer86.cn", "documents-open.offer86.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.86offer.com", "documents-admin.86offer.com", "documents-open.86offer.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["documents.86offer.cn", "documents-admin.86offer.cn", "documents-open.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

